FROM postgres:15.1-bullseye

# this is slow - updates all packages
RUN apt-get update && apt install -y postgresql-15-postgis-3 openjdk-17-jre


ENTRYPOINT ["/bin/bash", "-c", "/opt/tak/db-utils/configureInDocker.sh"]
